server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: c2e5934d12d8a87d9bf2f68d239d3e7f93b82fdb5e7b20f5ff15d8c01d72ab37
  lifetime: 1h



